version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: inicio123
      MYSQL_DATABASE: task_app_development
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      environment:
      DB_USERNAME: root
      DB_PASSWORD: inicio123
      DB_NAME: task_app_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
    volumes:
      - .:/task-app

volumes:
  mysql_data: